/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    12: typeof import('./pages/nav/1/2.vue')['default']
    2: typeof import('./pages/nav/2.vue')['default']
    4: typeof import('./pages/nav/dynamic-[id].vue')['default']
    AppLayout: typeof import('./layouts/AppLayout.vue')['default']
    BaseHeader: typeof import('./layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./layouts/BaseSide.vue')['default']
    copy: typeof import('./pages/nav/1/item-1 copy.vue')['default']
    Data: typeof import('./pages/nav/data/index.vue')['default']
    Dynamic: typeof import('./pages/nav/dynamic-[id].vue')['default']
    'Dynamic-[id]': typeof import('./pages/nav/dynamic-[id].vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Item1: typeof import('./pages/nav/1/item-1.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MessageBoxDemo: typeof import('./components/MessageBoxDemo.vue')['default']
    Pages: typeof import('./pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stress: typeof import('./pages/nav/tools/stress.vue')['default']
    Tools: typeof import('./pages/nav/tools/index.vue')['default']
    Users: typeof import('./pages/nav/users/index.vue')['default']
  }
}
